### PR TITLE
Update functional requirements

### PR DESCRIPTION
**Pull request by hothbert**

### CODE REVIEW

**Comment by hothbert** [comment]
its not finished yet but please check what ive done so far

**Review by rleslie0522 — APPROVED** [review]

**Comment by hothbert** [comment]
whoops i pressed enter before i finished my commit message, i meant to say "added more detail"

**Comment by hothbert** [comment]
I could do with some help with regards to changes we are going to make in functionality, but please approve this for now

**Review by caitlinthaeler — APPROVED** [review]
looks good

**Pull request merged**
